#  for test

version: "3.7"

services:

  s1: &template
    build: .
    command: ping baidu.com
    labels:
      - aginx.domain=s1.aginx.io

  s2:
    <<: *template
    ports:
      - 8500:8001
    labels:
      - aginx.domain=s2.aginx.io

  s21:
    <<: *template
    ports:
      - 8501:8001
    labels:
      - aginx.domain.8001=s2.aginx.io

  s3:
    <<: *template
    ports:
      - 8002:8001
    labels:
      - aginx.domain=s3.aginx.io,internal


  g11:
    <<: *template
    labels:
      - aginx.domain=g1.aginx.io,weight=1,internal
  g12:
    <<: *template
    labels:
      - aginx.domain=g1.aginx.io,weight=2,internal


  g21:
    <<: *template
    ports:
      - 8003:8001
    labels:
      - aginx.domain=g2.aginx.io,weight=1
  g22:
    <<: *template
    ports:
      - 8004:8001
    labels:
      - aginx.domain=g2.aginx.io,weight=2