# debug模式
debug = false
# 日志文件路径
log_path = ""

# http 监听端口
[http]
# 监听地址
address = "0.0.0.0"
# 监听端口
port = 10280

# 使用 Let's Encrypt 证书 - tls_enable为true优先使用本地证书模式
tls_encrypt_enable = false
# 域名列表
tls_encrypt_domain_names = ["examples.com"]

# 是否启用tls
tls_enable = false
# tls证书文件
[http.tls_config]
cert_file = "cert_file"
key_file = "key_file"


[[server]]
title = "etcd"
name = "etcd"
address = ["etcd:2379"]
key_prefix = "/aginx"
desc = "etcd"
roles = ["admin"]


## 以下为用户列表 ##
[[user]]
username = "admin"
password = "123456"
role = "admin"