version: '3'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3.18"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    ports:
      - 2379:2379
      - 2380:2380
  explorer:
    image: shiguanghuxian/etcd-manage:1.v2
    volumes:
      - ./cfg.toml:/app/config/cfg.toml
    ports:
      - "10280:10280"
    depends_on:
      - etcd