version: '3.7'

services:

  consul-agent: &consul-agent
    image: consul:latest
    networks:
      - consul-nw
    command: "agent -retry-join consul-server-bootstrap -bind '{{ GetInterfaceIP \"eth0\" }}' -client 0.0.0.0"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  consul-server:
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -bind '{{ GetInterfaceIP \"eth0\" }}' -client 0.0.0.0"
    labels:
      - aginx.domain.8500=server.d.la,internal
      - aginx.domain.8600=api.d.la
    deploy:
      mode: replicated
      replicas: 2

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8500:8500"
    command: "agent -server -ui -bind '{{ GetInterfaceIP \"eth0\" }}' -client 0.0.0.0"
    labels:
      - aginx.domain=consul.d.la
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  consul-nw:
    driver: overlay
    name: ${PROJECT_NAME:-example}